plugins:
  discourse_donations_enabled:
    default: false
    client: true
  discourse_donations_secret_key:
    client: false
  discourse_donations_public_key:
    client: true
  discourse_donations_enable_create_accounts:
    client: true
    default: false
  discourse_donations_description:
    client: true
    default: 'Donation'
  discourse_donations_currency:
    client: true
    default: 'USD'
  discourse_donations_hide_zip_code:
    default: true
    client: true
